spring:
  rabbitmq:
    host: node01
    port: 5672
    username: admin
    password: admin
    virtual-host:
    listener:
      simple:
        prefetch: 1
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: manual
        retry:
          multiplier: 1
          max-attempts: 3
      direct:
        retry:
          enabled: true
          max-attempts: 3

    # 以及被遗弃 发布者消息确认 代替的是publisher-confirm-type
#    publisher-confirms: true
    publisher-confirm-type: correlated
    publisher-returns: true

rabbbitmq:
  queue:
    routing:
      beijing: beijing-queue
      shanghai: shanghai-queue
    topic:
      beijing: beijing-queue
      shanghai: shanghai-queue
  exchange:
    routing: routing-topic-exchange
    topic: topic-topic-exchange